[package]
name = "webray-cli"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "WebGPU Powered Ray Tracer"
repository = "https://github.com/BLaZeKiLL/webray"
authors = ["Devashish Lal"]

[[bin]]
name = "webray-cli"
path = "src/main.rs"

[dependencies]
webray = { path = "../webray" }